### ISSUE TITLE
Code makes my eyes bleed

### ISSUE THREAD

**Issue by oliver-leung** [KyungSun4/im_bot-hi_bot#1]
The code in `hiimbot.py` is so atrocious, it probably violates some part of the Geneva Conventions. Can someone please refactor it so that blood will stop pouring out of my eyes?

**Comment by KyungSun4** [comment]
maybe someday before i see jeffery zhang so that he doesn't kill me

**Comment by oliver-leung** [comment]
@JeffreyZh4ng hello
